title = 'dados_orcamentarios'

[datapackages]

[datapackages.dados_siafi]
path = 'datapackages/dados_siafi/datapackage.yaml'

[datapackages.dados_aux_classificadores]
path = 'datapackages/dados_aux_classificadores/datapackage.yaml'
